### ISSUE TITLE
Enable Light And Dark Theme

### ISSUE THREAD

**Issue by m0hit-kumar** [Developer-Student-Clubs-MMDU/Hacktoberfest#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NNL-Keerthana** [comment]
HI!! I would like to work on this

**Comment by m0hit-kumar** [comment]
> HI!! I would like to work on this

sure, you can start working on it

**Comment by kritika902** [comment]
Please assign it to me.

**Comment by m0hit-kumar** [comment]
> Please assign it to me.

you can start working on it @kritika902
